force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Tot_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tot_Amount__c</fullName>
    <description>Tot Amount</description>
    <label>Tot Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProjectHelper1.cls
/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                                                                           ║
 * ║   ██████╗ ██████╗  ██████╗      ██╗███████╗ ██████╗████████╗              ║
 * ║   ██╔══██╗██╔══██╗██╔═══██╗     ██║██╔════╝██╔════╝╚══██╔══╝              ║
 * ║   ██████╔╝██████╔╝██║   ██║     ██║█████╗  ██║        ██║                 ║
 * ║   ██╔═══╝ ██╔══██╗██║   ██║██   ██║██╔══╝  ██║        ██║                 ║
 * ║   ██║     ██║  ██║╚██████╔╝╚█████╔╝███████╗╚██████╗   ██║                 ║
 * ║   ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚══════╝ ╚═════╝   ╚═╝                 ║
 * ║                      ██╗  ██╗███████╗██╗     ██████╗ ███████╗██████╗      ║
 * ║                      ██║  ██║██╔════╝██║     ██╔══██╗██╔════╝██╔══██╗     ║
 * ║                      ███████║█████╗  ██║     ██████╔╝█████╗  ██████╔╝     ║
 * ║                      ██╔══██║██╔══╝  ██║     ██╔═══╝ ██╔══╝  ██╔══██╗     ║
 * ║                      ██║  ██║███████╗███████╗██║     ███████╗██║  ██║     ║
 * ║                      ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝     ║
 * ║                                                                           ║
 * ╠═══════════════════════════════════════════════════════════════════════════╣
 * ║ Title       : ProjectHelper                                               ║
 * ║ Description : Unoptimized class version on Project__c                     ║
 * ║ Author      : Shane Khotsoka                                              ║
 * ║ Created     : 2024-09-16                                                  ║
 * ║ Version     : 1.0                                                         ║
 * ╠═══════════════════════════════════════════════════════════════════════════╣
 * ║ Modification History:                                                     ║
 * ║ 2024-09-17 : Shane Khotsoka - Initial version                             ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 *
 * @description This ProjectHelper class contains a updateProjectAmount method for querying a Project__c (Projects) related Project Tasks.
 * It includes a for loop for iterating/looping through the task amounts and adding it to the project's total Amount.
 *
 * @see ProjectTrigger1
 */

public with sharing class ProjectHelper1 {
    public static void updateProjectAmounts1(Project__c project) {
        //Query the project task related to the project 
        List<Project_Task__c> tasks = [SELECT Amount__c 
        FROM Project_Task__c 
        WHERE Project__c = :project.Id];

        Decimal totalAmount = 0;
        //iterate through the project task and add the task amounts to the project total amount
        for (Project_Task__c task : tasks) {
            //iterate and add all task amount to the total amount variable
            totalAmount += task.Amount__c;
        }
        //assign the total amount to the project total amount field
        project.Tot_Amount__c = totalAmount;
    }
}